// import "./globals.css";
import "tailwindcss/tailwind.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata = {
  title: "Bloggy",
  description: "Generated by Muhammad Sufyan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
